MAX_MEMORY = 100_000
BATCH_SIZE = 1000
LR = 0.001

MODEL_INPUT_SIZE = 4
MODEL_HIDDEN_SIZE = 256
MODEL_OUTPUT_SIZE = 3

INITIAL_BALANCE = 10000.0
GAMMA = 0.9

EPSILON_START = 80
EPSILON_DECAY_RATE = 1
EPSILON_MIN = 0

ACTION_CLOSE = 0
ACTION_LONG = 1  
ACTION_SHORT = 2

REWARD_PROFIT = 10
REWARD_LOSS = -10

REQUIRED_CSV_COLUMNS = ['timestamp', 'open', 'high', 'low', 'close', 'volume']

MARKET_GAP_THRESHOLD_HOURS = 2

FEATURE_MOMENTUM_LOOKBACK = 5
FEATURE_MOMENTUM_CLIP = 0.05
FEATURE_PNL_CLIP = 0.2

LOG_INTERVAL = 10
CHECKPOINT_INTERVAL = 100

PLOT_DPI = 300
PLOT_FIGSIZE_EQUITY = (12, 6)
PLOT_FIGSIZE_ANALYSIS = (15, 10)